### ISSUE TITLE
Undefined index: DEFAULT_USER_ID_TTD_SK_KELULUSAN

### ISSUE THREAD

**Issue by mrizkir** [stmikbdgbali/simak#39]
Production.ERROR: Undefined index: DEFAULT_USER_ID_TTD_SK_KELULUSAN {"exception":"[object] (ErrorException(code: 0): Undefined index: DEFAULT_USER_ID_TTD_SK_KELULUSAN at vendor/illuminate/collections/Collection.php:1424)
[stacktrace]

#0 vendor/illuminate/collections/Collection.php(1424): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(8, 'Undefined index...', '/home/u1476265/...', 1424, Array)
#1 app/Http/Controllers/SPMB/SKKelulusanController.php(112): Illuminate\\Support\\Collection->offsetGet('DEFAULT_USER_ID...')
#2 vendor/illuminate/container/BoundMethod.php(36): App\\Http\\Controllers\\SPMB\\SKKelulusanController->printtopdf1(Object(Laravel\\Lumen\\Http\\Request), '81826b0c-7df8-4...')
#

**Comment by stmikbdgbali** [comment]
fixed.
